# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fd9d9600937215c541f99ad9c2522f79b3370686fe7b3972af0b8a9d1b8abef9086bb6232de1c01867eca30ff554afbf880d9723440fc260a8e077bd33fe515

test:
  secret_key_base: bb790ddb0e69851eb5a13bd58c004e7755a6578843a5dced0462e99af4cfc1597d807206d4c90673dc5915bd2d69fdadcd4cddb89692039fbc5545d31e865c16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
